// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLChe8DT8ZaQNFJs0qNd0Gm4fExGozwB4',
    appId: '1:177460389221:web:de4d9e2ec601442857ad8c',
    messagingSenderId: '177460389221',
    projectId: 'moviles-2-23c17',
    authDomain: 'moviles-2-23c17.firebaseapp.com',
    databaseURL: 'https://moviles-2-23c17-default-rtdb.firebaseio.com',
    storageBucket: 'moviles-2-23c17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWCx7jZxY2rMYUZS5BzK9dcarcn_eV-g',
    appId: '1:177460389221:android:afaf743b4e6fbab057ad8c',
    messagingSenderId: '177460389221',
    projectId: 'moviles-2-23c17',
    databaseURL: 'https://moviles-2-23c17-default-rtdb.firebaseio.com',
    storageBucket: 'moviles-2-23c17.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcxg9P9pm4gMH9XGeeh2LjyodxZjWNwQQ',
    appId: '1:177460389221:web:9cafd238e62cc4e657ad8c',
    messagingSenderId: '177460389221',
    projectId: 'moviles-2-23c17',
    authDomain: 'moviles-2-23c17.firebaseapp.com',
    databaseURL: 'https://moviles-2-23c17-default-rtdb.firebaseio.com',
    storageBucket: 'moviles-2-23c17.appspot.com',
  );
}
